apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mmct4ipi8-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mmct4ipi8-java-springboot-gitops